package com.example.nexus.notification;

public enum NotificationType {
    NEW_MESSAGE,
    NEW_REVIEW,
    NEW_PARTICIPANT,
    PARTICIPATION_APPROVED,
    PARTICIPATION_REJECTED,
    PARTICIPATION_COMPLETED,
    REWARD_PAID,
    TEST_UPDATE,
    GENERAL_ANNOUNCEMENT,
    MESSAGE
}
